# Configs

#PROMETHEUS_IP = '10.106.36.184'
PROMETHEUS_IP = '10.42.0.9'
PROMETHEUS_PORT = '9090'

WEBSERVER_DEUBG = True
WEBSERVER_HOST = '0.0.0.0'
WEBSERVER_PORT = '8888'

HAPROXY_IP = '10.97.177.199'
HAPROX_PORT = '80'

SERVICE_NAME = 'nodejs-arml-service'
METRIC_NAME = 'qps'
CPU_METRIC_NAME = 'cpu'
NAMESPACE = 'default'
LABEL_NAME = 'tradeoff'
DEPLOYMENT_NAME = 'nodejs-arml-deployment'

# Relative error is between -2 and 2; 0 is the best
GRADE_THRESHOLD = 1.1

TRAINING_TIME_INTERVAL_MINUTES = 20
VALUE_TIME_INTERVAL_SEC = '1s'
WAITING_TIME_AFTER_CREATION_SEC = 20
